# Generated by Django 3.0.3 on 2020-02-28 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_iface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default='00:00')),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('end_time', models.TimeField(default='00:00')),
            ],
            options={
                'verbose_name': 'reservations',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_iface.Reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_iface.Room')),
            ],
            options={
                'verbose_name': 'reserved rooms',
                'ordering': ['reservation_id'],
            },
        ),
    ]
