# Generated by Django 3.0.3 on 2020-03-02 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0002_auto_20200301_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedResData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(default='', max_length=10)),
                ('manager_email', models.EmailField(default=None, max_length=254)),
                ('manager_name', models.CharField(default='', max_length=20, null=True)),
                ('cust_email', models.EmailField(default=None, max_length=254)),
                ('cust_name', models.CharField(default='', max_length=20, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default='00:00')),
                ('end_time', models.TimeField(default='00:00')),
            ],
        ),
    ]
