# Generated by Django 3.0.3 on 2020-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0005_auto_20200302_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolatedresdata',
            name='end_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='start_time',
            field=models.CharField(max_length=5),
        ),
    ]
