# Generated by Django 3.0.3 on 2020-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0007_auto_20200302_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolatedresdata',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
