# Generated by Django 3.0.3 on 2020-03-02 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0008_auto_20200302_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolatedresdata',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 2)),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='end_time',
            field=models.TimeField(verbose_name=datetime.time(16, 36, 3, 357198)),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='start_time',
            field=models.TimeField(verbose_name=datetime.time(16, 36, 3, 357181)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 2)),
        ),
    ]
