# Generated by Django 3.0.3 on 2020-03-02 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0009_auto_20200302_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolatedresdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='isolatedresdata',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
