# Generated by Django 3.0.3 on 2020-03-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_iface', '0010_auto_20200302_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isolatedresdata',
            options={'ordering': ['-date'], 'verbose_name': 'isolated reservation data'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date'], 'verbose_name': 'reservation'},
        ),
        migrations.AddField(
            model_name='isolatedresdata',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
