# Generated by Django 3.0.3 on 2020-03-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200304_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='instance',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
