# Generated by Django 3.0.3 on 2020-03-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('advance_period', models.IntegerField(default=10)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'room',
                'ordering': ['room_no'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='00:00')),
                ('end_time', models.TimeField(default='00:00')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_iface.Room')),
            ],
            options={
                'verbose_name': 'slot',
                'ordering': ['start_time'],
            },
        ),
    ]
