# Generated by Django 3.0.3 on 2020-02-28 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('advance_period', models.IntegerField(default=10)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'rooms',
                'ordering': ['room_no'],
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default='00:00')),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('end_time', models.TimeField(default='00:00')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_iface.Room')),
            ],
            options={
                'verbose_name': 'availbale slots',
                'ordering': ['room'],
            },
        ),
    ]
