# Generated by Django 3.0.3 on 2020-03-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('manager_iface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Manager'),
        ),
    ]
