# Generated by Django 3.0.3 on 2020-03-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_iface', '0003_auto_20200302_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'slot'},
        ),
    ]
