# Generated by Django 3.0.3 on 2020-03-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_iface', '0005_auto_20200302_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='manager_iface.Room'),
        ),
    ]
